services:
  # Servicio CEP Sunat API
  cpe-sunat-principal:
    # Construcción de la imagen a partir del Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/syssoftintegra/cpe-sunat:latest
    # Red
    networks:
    - luis
    # Volumen
    volumes:
      - cpe-sunat-volumen:/var/www/html/storage/app/files
    # Comando para reiniciar el contenedor
    restart: always
    # Nombre del contenedor
    container_name: cpe-sunat-principal

# Red compartida entre servicios
networks:
  luis:
    external: true

# Volúmenes (persistencia)
volumes:
  cpe-sunat-volumen: