services:
  # Servicio CEP Sunat API
  cpe-sunat-principal:
    # Construcción de la imagen a partir del Dockerfile
    build: 
      context: .
      dockerfile: Dockerfile
    image: cpe-sunat-principal-image
    # Red
    networks:
    - luis
    # Volumen
    volumes:
      - cpe-sunat-volumen:/var/www/html/storage/app/files
    # Nombre del contenedor
    restart: always
    container_name: cpe-sunat-principal

# Red compartida entre servicios
networks:
  luis:
    external: true

# Volúmenes (persistencia)
volumes:
  cpe-sunat-volumen: